# Generated by Django 5.2.8 on 2025-11-26 02:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Categoria')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Subcategoria (Franquicia)')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sku', models.CharField(editable=False, help_text='Codigo autogenerado (unico), Ej: MC-0001', max_length=50, unique=True, verbose_name='Codigo SKU')),
                ('nombre', models.CharField(help_text='Ej: Starter Deck Digimon TCG Double Typhoon', max_length=250, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('precio', models.DecimalField(decimal_places=0, help_text='Precio en pesos Chilenos', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Precio de Venta')),
                ('stock', models.IntegerField(default=0, help_text='Cantidades de unidades disponibles', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Disponible')),
                ('activo', models.BooleanField(default=True, verbose_name='Producto Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria', verbose_name='Categoria')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.subcategoria', verbose_name='Subcategoria (Franquicia)')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['codigo_sku'],
            },
        ),
    ]
