# Generated by Django 5.2.8 on 2025-11-26 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_critico',
            field=models.IntegerField(default=2, help_text='Cantidad que activa alerta de stock critico', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Critico (Alerta Critica)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=5, help_text='Cantidad que activa alerta de stock bajo', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Minimo (Alerta Baja)'),
        ),
    ]
