# Generated by Django 5.2.8 on 2025-11-27 11:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_stock_critico_producto_stock_minimo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('VENTA', 'Venta'), ('ANULACION', 'Anulacion de Venta')], max_length=20)),
                ('cantidad', models.IntegerField(help_text='Cantidad del movimiento (siempre positiva)', validators=[django.core.validators.MinValueValidator(1)])),
                ('stock_anterior', models.IntegerField(verbose_name='Stock antes del movimiento')),
                ('stock_nuevo', models.IntegerField(verbose_name='Stock despues del movimiento')),
                ('motivo', models.CharField(help_text='Ej: Ajuste, Compra a proveedor, Venta, etc', max_length=255, verbose_name='Motivo del movimiento')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.producto')),
                ('usuario', models.ForeignKey(null='True', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
