# Generated by Django 5.2.8 on 2025-12-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_movimientostock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del producto (opcional). Formatos: JPG, PNG', null=True, upload_to='productos/', verbose_name='Imagen del Producto'),
        ),
    ]
