# Generated by Django 5.2.8 on 2025-12-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_venta_detalleventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='iva',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='IVA (19%)'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Subtotal (neto)'),
        ),
    ]
