# Generated by Django 5.2.8 on 2025-12-27 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
        ('inventario', '0006_venta_iva_alter_venta_subtotal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Número de Pedido')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Pedido')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='IVA (19%)')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Total')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pagado'), ('LISTO', 'Listo para Retiro'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado del Pedido')),
                ('token_ws', models.CharField(blank=True, max_length=100, null=True, verbose_name='Token Webpay')),
                ('buy_order', models.CharField(blank=True, max_length=100, null=True, verbose_name='Orden de Compra')),
                ('transaction_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Transacción')),
                ('authorization_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Autorización')),
                ('payment_type_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo de Pago')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=0, help_text='Precio al momento de la compra (IVA incluido)', max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=0, help_text='Cantidad × Precio Unitario', max_digits=10, verbose_name='Subtotal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto', verbose_name='Producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='carrito.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
                'ordering': ['id'],
            },
        ),
    ]
